#!/usr/bin/perl -w
use strict;
use warnings;

### after: use lib qw(@RT_LIB_PATH@);
use lib qw(/opt/rt4/local/lib /opt/rt4/lib);

use RT;
BEGIN { RT::LoadConfig(); RT::Init(); }

use RT::Migrate;
use RT::Migrate::Importer;
use Getopt::Long;
use Pod::Usage qw//;
use Time::HiRes qw//;

my %OPT;
GetOptions(
    \%OPT,
    "preserve-tickets|t!",
    "originalid|i=s",
);

my $import;

my $progress,
my ($summary) = grep {-f $_} map {"$_/rt-serialized"} @ARGV;
if ($summary) {
    my $ref = Storable::retrieve($summary);
    $progress = RT::Migrate::progress(
        counts => sub { $import->ObjectCount },
        max    => $ref->{counts},
    );
}

$import = RT::Migrate::Importer->new(
    PreserveTicketIds => $OPT{'preserve-tickets'},
    OriginalId        => $OPT{originalid},
    Progress          => $progress,
);
my @files = map {-d $_ ? <$_/*.dat> : $_} @ARGV;
my %counts = $import->Import( @files );

print "Total object counts:\n";
for (sort {$counts{$b} <=> $counts{$a}} keys %counts) {
    printf "%8d %s\n", $counts{$_}, $_;
}
